import React from 'react';
import {Link} from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import Icon from '../components/Icon';
import {deleteLocalData} from '../lib/persist';
import {toast} from '../lib/toast';
import {journalTemplates} from '../lib/journalContent';
import {screeners} from '../lib/screeningContent';
import meta from '../content/meta.json';
import {leaves,diagnosisGroups,medications,treatmentGuides} from '../lib/content';
export default function About() {
 return <div className="container"><PageHeader title="О PsyParent" subtitle="Понятная информация после приёма и опора для следующего разговора с врачом." backTo="/" backLabel="Главная"/><div className="stack">
 <section className="card"><div className="eyebrow">Автор проекта</div><h2>Степан Краснощеков</h2><p style={{marginTop:10}}>Детский психиатр. Справочные материалы опираются на международные клинические рекомендации, документы профессиональных обществ и исследования. Ссылки и ограничения указаны в каждой карточке.</p><p>В справочнике {leaves.length} тем в {diagnosisGroups.length} разделах: развитие, тревога, настроение, стресс, поведение, питание и другие трудности. Есть {medications.length} карточек препаратов, добавок и памяток и {treatmentGuides.length} разборов назначений. Есть 11 карточек специалистов и немедикаментозная помощь ко всем 69 темам. В разделе «Тесты» {screeners.length} инструментов. PHQ-9, GAD-7 и рабочую русскую форму SNAP-IV можно пройти здесь; для внешних форм можно сохранить результат, а YGTSS-R с перечнем тиков и критериями оценок заполняется со специалистом. Доступны {journalTemplates.length} дневников и форм наблюдений: история, редактирование, сравнение числовых записей и выбор для памятки. Обзоры и жизненные ситуации отмечены отдельно от диагнозов.</p><p className="small muted">Связи с диагнозами включают лечение, сопутствующие задачи, побочные эффекты и назначения с недостаточными доказательствами. Наличие карточки не означает рекомендацию средства.</p><a href="https://t.me/doc_kras" target="_blank" rel="noopener noreferrer" className="btn secondary compact" style={{marginTop:16}}>Канал автора<Icon name="external" size={15}/></a></section>
 <section className="card"><h2>Как пользоваться</h2><ol><li>Выберите диагноз, который указан в заключении.</li><li>Посмотрите, что стоит уточнить и какая помощь бывает полезна.</li><li>Разберите назначенный препарат и сохраните нужные вопросы.</li><li>Выберите специалистов и немедикаментозные методы в разделе «Помощь» нужного диагноза.</li><li>Выберите тест по возрасту и задаче. Уточните, кто отвечает и где открывается форма, затем сохраните полученный результат.</li><li>В разделе «Дневники и формы» можно описать сон, поведение, переносимость лечения, навыки и жалобы. Выберите нужные записи для передачи врачу.</li><li>Откройте «К врачу» и скопируйте или скачайте памятку.</li></ol><p className="small muted">{meta.disclaimer}</p></section>
 <section className="card"><h2>Ваши записи</h2><ul><li>Вопросы, наблюдения, назначения, дневники и сохранённые результаты скринингов с ответами сохраняются локально, в этом браузере или окне Telegram.</li><li>Приложение не отправляет содержимое памятки на свой сервер или врачу. Вы сами решаете, кому передать скопированный текст или файл.</li><li>После очистки данных браузера записи могут исчезнуть. На другом устройстве они не синхронизируются.</li><li>Доступ к этому устройству и браузеру может означать доступ к записям. Не добавляйте лишние персональные сведения.</li></ul><button className="btn danger" onClick={()=>{if(window.confirm('Удалить все записи PsyParent на этом устройстве, включая памятку, историю скринингов с ответами, дневники и отметки в карточках? Это действие нельзя отменить.')){if(deleteLocalData())toast('Все локальные записи удалены');}}}><Icon name="trash" size={16}/>Удалить все мои записи</button></section>
 <div className="callout"><strong>Если заметили неточность</strong><p>Сохраните название карточки и описание проблемы, чтобы передать автору. Не прикладывайте персональные данные ребёнка.</p></div>
 <p className="small muted">Пилотная версия {meta.appVersion}. Обновление материалов: {new Date(meta.contentVersion+'T12:00:00').toLocaleDateString('ru-RU')}. Материалы прошли редакционный пересмотр. Окончательное утверждение автором и проверка в реальном Telegram перед публичным запуском ещё предстоят.</p>
 <Link className="btn secondary" to="/help">Когда нужна срочная помощь</Link>
 </div></div>;
}
