import React from 'react';
import {Link,useLocation,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {journalTemplate,journalTemplates,journalValueLabel} from '../lib/journalContent';
import {canCompareJournals,filterJournals,formatJournals,includeJournals,journalAlerts,journalPeriod,removeJournal} from '../lib/journals';
import {useJournals} from '../lib/useJournals';
import {respondentLabels,Respondent} from '../lib/screeningContent';
import {downloadText} from '../lib/export';
import {toast} from '../lib/toast';
import PageHeader from '../components/PageHeader';
import JournalRecordCard from '../components/JournalRecordCard';
import TrendChart from '../components/TrendChart';
const setIncluded=(ids:string[],value:boolean)=>{if(!includeJournals(ids,value))toast('Не удалось изменить выбор',{variant:'error'});};
export default function JournalHistory(){
 const rows=useJournals(),[params,setParams]=useSearchParams(),location=useLocation();
 const change=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next,{replace:true});};
 const f=Object.fromEntries(params.entries()),shown=filterJournals(rows,f),t=journalTemplate(f.template||''),fields=t?.fields.filter(field=>field.trend&&field.type==='number')||[];
 const comparable=Boolean(t&&canCompareJournals(shown,t)),days=shown.slice().reverse();
 return <div className="container"><PageHeader title="История дневников" subtitle="Выберите записи одного ребёнка, чтобы подготовиться к приёму." backTo="/forms" backLabel="Все формы"/>
 {!rows.length?<div className="emptyState"><h2>Пока нет сохранённых записей</h2><p>Выберите нужную форму. Одного короткого наблюдения достаточно, чтобы начать.</p><Link className="btn" to="/forms">Выбрать форму</Link></div>:<>
 <section className="card noPrint"><div className="journalFields">
 <div><label className="fieldLabel" htmlFor="jh-child">Ребёнок</label><select id="jh-child" value={f.child||''} onChange={e=>change('child',e.target.value)}><option value="">Все дети</option>{[...new Set(rows.map(r=>r.childLabel))].map(v=><option key={v}>{v}</option>)}</select></div>
 <div><label className="fieldLabel" htmlFor="jh-template">Форма</label><select id="jh-template" value={f.template||''} onChange={e=>change('template',e.target.value)}><option value="">Все формы</option>{journalTemplates.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></div>
 <div><label className="fieldLabel" htmlFor="jh-respondent">Кто заполнял</label><select id="jh-respondent" value={f.respondent||''} onChange={e=>change('respondent',e.target.value)}><option value="">Все отвечающие</option>{[...new Set(rows.map(r=>r.respondent))].map(v=><option key={v} value={v}>{respondentLabels[v as Respondent]}</option>)}</select></div>
 <div><label className="fieldLabel" htmlFor="jh-observer">Наблюдатель</label><select id="jh-observer" value={f.observer||''} onChange={e=>change('observer',e.target.value)}><option value="">Все наблюдатели</option>{[...new Set(rows.map(r=>r.observerLabel).filter(Boolean))].map(v=><option key={v}>{v}</option>)}</select></div>
 <div><label className="fieldLabel" htmlFor="jh-from">Дата / конец периода от</label><input className="input" id="jh-from" type="date" value={f.from||''} onChange={e=>change('from',e.target.value)}/></div>
 <div><label className="fieldLabel" htmlFor="jh-to">До</label><input className="input" id="jh-to" type="date" value={f.to||''} onChange={e=>change('to',e.target.value)}/></div>
 </div>{params.size>0&&<button className="textButton" onClick={()=>setParams({},{replace:true})}>Сбросить фильтры</button>}</section>
 <p className="searchMeta" role="status">Показано: {shown.length} из {rows.length}. В памятке врачу: {rows.filter(r=>r.includeInVisit).length}.</p>
 {f.from&&f.to&&f.from>f.to&&<p className="callout">Дата начала фильтра позже даты конца. Исправьте диапазон.</p>}
 {!!shown.length&&<div className="buttonRow journalButtons noPrint"><button className="btn secondary" onClick={()=>downloadText(formatJournals(shown),'Kora-dnevniki.txt')}>Скачать показанные .txt</button><button className="btn secondary" onClick={()=>setIncluded(shown.map(r=>r.id),true)}>Включить показанные в памятку</button><button className="textButton" onClick={()=>setIncluded(shown.map(r=>r.id),false)}>Убрать показанные из памятки</button></div>}
 {t&&fields.length>0&&<section className="card" style={{margin:'20px 0'}}><h2>Наблюдения по датам</h2>{comparable?<><p className="small muted">{shown[0].childLabel} · {respondentLabels[shown[0].respondent]} · {shown[0].observerLabel}. Периоды одинаковой длительности; пустое поле показано как «—». Это внесённые значения, без оценки причин изменений.</p><div className="trendGridWrap">{fields.map(field=><TrendChart key={field.id} title={field.label} points={days.map(r=>({label:new Date(r.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'}),value:r.values[field.id]?Number(r.values[field.id]):null}))}/>)}</div><div className="journalTable" tabIndex={0} role="region" aria-label="Сравнение записей"><table><thead><tr><th>Дата / период</th>{fields.map(field=><th key={field.id}>{field.label}</th>)}<th>Лечение / занятия</th></tr></thead><tbody>{days.map(r=><tr key={r.id}><th><Link to={'/forms/record/'+r.id}>{journalPeriod(r)}</Link></th>{fields.map(field=><td key={field.id}>{r.values[field.id]??'—'}</td>)}<td>{r.treatment||'Не указано'}</td></tr>)}</tbody></table></div></>:<p className="small muted">Для сравнения нужны хотя бы две записи одной формы об одном ребёнке, от одного указанного наблюдателя, за периоды одинаковой длительности. Для целей и навыков также должны совпадать выбранная задача и единицы измерения. Уточните фильтры или записи.</p>}</section>}
 <div className="stack">{shown.map(r=>{const form=journalTemplate(r.templateId)!,first=form.fields.find(field=>r.values[field.id]);return <article className="card" key={r.id}><span className="tag neutral">{form.domain}</span><h2><Link to={'/forms/record/'+r.id} state={{from:location.pathname+location.search}}>{form.title}</Link></h2><p style={{marginTop:10}}><strong>{r.childLabel}</strong> · {journalPeriod(r)}</p><p className="small muted">{respondentLabels[r.respondent]}{r.observerLabel?' · '+r.observerLabel:''}</p>{first&&<p className="journalExcerpt">{first.label}: {journalValueLabel(first,r.values[first.id])}</p>}{journalAlerts(r).length>0&&<p className="callout danger">В записи есть повод обратиться за помощью раньше. Откройте её, чтобы прочитать пояснение.</p>}<label className="selectionCheck"><input type="checkbox" checked={r.includeInVisit} onChange={e=>setIncluded([r.id],e.target.checked)}/><span>Включить в памятку врачу</span></label><div className="buttonRow journalButtons"><Link className="btn secondary compact" to={'/forms/record/'+r.id} state={{from:location.pathname+location.search}}>Открыть запись</Link><Link className="textButton" to={'/forms/'+r.templateId+'?copy='+r.id}>Следующая запись</Link></div></article>;})}</div>
 {!shown.length&&<p className="callout">Записей для этого выбора нет. Измените фильтры или добавьте наблюдение.</p>}<Link className="btn full" to="/visit" style={{marginTop:20}}>Открыть памятку врачу</Link></>}
 <p className="privacyNote">Снятие отметки не удаляет запись. На общем устройстве история доступна другим пользователям браузера. Передавайте только те сведения, которыми готовы поделиться.</p></div>;
}
export function JournalSavedRecord(){
 const {recordId=''}=useParams(),rows=useJournals(),r=rows.find(x=>x.id===recordId),nav=useNavigate(),location=useLocation();
 const back=typeof location.state?.from==='string'&&location.state.from.startsWith('/forms/history')?location.state.from:'/forms/history';
 if(!r)return <div className="container"><PageHeader title="Запись не найдена" backTo="/forms/history" backLabel="История"/><p>Возможно, запись удалена или сохранена в другом браузере. Ссылка не переносит её между устройствами.</p></div>;
 return <div className="container"><PageHeader title="Сохранённая запись" backTo={back} backLabel="История дневников"/><JournalRecordCard record={r}/><div className="noPrint"><label className="selectionCheck"><input type="checkbox" checked={r.includeInVisit} onChange={e=>setIncluded([r.id],e.target.checked)}/><span>Включить в памятку врачу</span></label><div className="buttonRow journalButtons"><Link className="btn" to={'/forms/'+r.templateId+'?copy='+r.id}>Следующая запись</Link><Link className="btn secondary" to={'/forms/'+r.templateId+'?edit='+r.id}>Редактировать</Link><Link className="btn secondary" to="/visit">К памятке врачу</Link></div><button className="textButton danger" onClick={()=>{if(window.confirm('Удалить эту запись из истории и памятки?')){if(removeJournal(r.id)){toast('Запись удалена');nav(back,{replace:true});}else toast('Не удалось удалить запись',{variant:'error'});}}}>Удалить запись</button></div></div>;
}
