import React,{useEffect,useRef,useState} from 'react';
import {useDraft} from '../lib/drafts';
import DraftNotice from '../components/DraftNotice';
import {Link,useParams,useLocation} from 'react-router-dom';
import {screenerById,respondentLabels,impactOptions,screeningSafety,sdqFields,formFor,sectionAt,Screener,Respondent} from '../lib/screeningContent';
import {createScreening,localDate,saveScreening,validateScreening,ScreeningInput,ScreeningResult} from '../lib/screenings';
import {toast} from '../lib/toast';
import PageHeader from '../components/PageHeader';
import Disclosure from '../components/Disclosure';
import Icon from '../components/Icon';
import Sources from '../components/Sources';
import ClinicalInventory from '../components/ClinicalInventory';
import ExtraScaleFields from '../components/ExtraScaleFields';
import {extraIds} from '../lib/extraScreeningScoring';
import {downloadClinicalForm} from '../lib/clinicalForm';
import ScreeningResultCard from '../components/ScreeningResultCard';
import {trackRecent} from '../lib/recent';
import ChildQuickFill from '../components/ChildQuickFill';
import {childAge,getChildren} from '../lib/children';
export default function ScreeningDetail(){const {id=''}=useParams(),s=screenerById(id),location=useLocation();return s?<ScreeningForm key={s.id} s={s} backTo={location.state?.from?.startsWith('/screenings?')?location.state.from:'/screenings'}/>:<div className="container"><PageHeader title="Такого опросника пока нет" backTo="/screenings" backLabel="Все скрининги"/></div>;}
function ScreeningForm({s,backTo}:{s:Screener;backTo:string}){
 useEffect(()=>{trackRecent('scr',s.id);},[s.id]);
 // With a single child profile the name and age are filled in at once; the age follows the chosen date.
 const only=()=>{const list=getChildren();return list.length===1?list[0]:undefined;},ageOf=(c:ReturnType<typeof only>,on:string)=>c?String(s.ageUnit==='months'?childAge(c,on).months:childAge(c,on).years):'';
 const [childLabel,setChildLabel]=useState(()=>only()?.label||''),[age,setAge]=useState(()=>ageOf(only(),localDate())),[respondent,setRespondent]=useState<Respondent>(s.respondents[0]),[date,setDate]=useState(localDate),[notes,setNotes]=useState('');
 const [answers,setAnswers]=useState<number[]>(Array(formFor(s,s.respondents[0])?.questions.length||0).fill(-1)),[impact,setImpact]=useState(''),[total,setTotal]=useState(''),[followUpDone,setFollowUpDone]=useState(''),[followUpScore,setFollowUpScore]=useState(''),[subscales,setSubscales]=useState<Record<string,string>>({});
 const [ticInventory,setTicInventory]=useState<string[]>([]);
 const [measurements,setMeasurements]=useState<Record<string,string>>({}),[sourceForm,setSourceForm]=useState(s.translation),[clinicianConfirmed,setClinicianConfirmed]=useState(false);
 const [errors,setErrors]=useState<string[]>([]),[result,setResult]=useState<ScreeningResult|null>(null),[saved,setSaved]=useState(false),[saveError,setSaveError]=useState(false);
 const resultRef=useRef<HTMLDivElement>(null),errorsRef=useRef<HTMLDivElement>(null);
 // Long questionnaires keep a draft on the device until the result is saved.
 const draftValue={childLabel,age,respondent,date,notes,answers,impact,total,followUpDone,followUpScore,subscales,ticInventory,measurements,sourceForm,clinicianConfirmed};
 const draft=useDraft('screening.'+s.id,draftValue,d=>{setChildLabel(d.childLabel);setAge(d.age);setRespondent(d.respondent);setDate(d.date);setNotes(d.notes);setAnswers(d.answers);setImpact(d.impact);setTotal(d.total);setFollowUpDone(d.followUpDone);setFollowUpScore(d.followUpScore);setSubscales(d.subscales);setTicInventory(d.ticInventory);setMeasurements(d.measurements);setSourceForm(d.sourceForm);setClinicianConfirmed(d.clinicianConfirmed);});
 const form=formFor(s,respondent),selfOnly=s.respondents.length===1&&s.respondents[0]==='self',byAdult=!s.respondents.includes('self');
 const follow=total!==''&&Number(total)>=3&&Number(total)<=7,safety=s.id==='phq9'&&answers[8]>0;
 const submit=(event:React.FormEvent)=>{
  event.preventDefault();
  const input:ScreeningInput={childLabel,age:age===''?NaN:Number(age),respondent,completedDate:date,notes};
  if(s.mode==='embedded'){input.answers=answers;if(impact!=='')input.impact=Number(impact);}
  else if(s.mode==='external')input.total=total===''?NaN:Number(total);
  if(s.id==='mchat'&&follow){if(followUpDone!=='')input.followUpDone=followUpDone==='yes';if(followUpDone==='yes')input.followUpScore=followUpScore===''?NaN:Number(followUpScore);}
  if(s.id==='sdq')input.subscales=Object.fromEntries(Object.entries(subscales).filter(([,v])=>v!=='').map(([k,v])=>[k,Number(v)]));
  if(extraIds.includes(s.id)){input.measurements=Object.fromEntries(Object.entries(measurements).filter(([,v])=>v!=='').map(([k,v])=>[k,Number(v)]));input.sourceForm=sourceForm;if(s.mode==='clinical'){input.clinicianConfirmed=clinicianConfirmed;input.ticInventory=ticInventory;}}
  const issues=validateScreening(s.id,input);setErrors(issues);
  if(issues.length){requestAnimationFrame(()=>errorsRef.current?.focus());return;}
  setResult(createScreening(s.id,input));setSaved(false);setSaveError(false);requestAnimationFrame(()=>{resultRef.current?.focus();window.scrollTo(0,0);});
 };
 return <div className="container"><PageHeader title={s.name+' · '+s.title} subtitle={s.ageLabel} backTo={backTo} backLabel="Все скрининги"/>
 {result?<div ref={resultRef} tabIndex={-1}>
 <div className={'callout '+(!saved?'warn':'')} style={{marginBottom:16}} role="status"><strong>{saved?(result.includeInVisit?'Результат сохранён в историю и памятку':'Результат сохранён только в историю'):'Результат ещё не сохранён'}</strong><p>{saved?'В разделе «К врачу» можно выбрать, какие записи передать врачу.':'Сохраните его кнопкой ниже или скачайте файл. При закрытии страницы несохранённый результат исчезнет.'}</p></div>
 {!saved&&<button className="btn full" style={{marginBottom:16}} onClick={()=>{const ok=saveScreening(result);setSaved(ok);setSaveError(!ok);if(ok){draft.clear();}toast(ok?'Результат сохранён':'Не удалось сохранить. Скопируйте или скачайте результат.',{variant:ok?'success':'error'});}}><Icon name="plus" size={17}/>{s.id==='crafft'?'Сохранить только в историю':'Сохранить в историю и памятку'}</button>}
 {saveError&&<p className="callout danger" role="alert" style={{marginBottom:16}}>Браузер не сохранил запись. Результат остаётся на этом экране: скопируйте или скачайте его перед закрытием.</p>}
 <ScreeningResultCard result={result}/>
 <div className="buttonRow" style={{marginTop:18}}>{saved?<><Link className="btn" to="/visit">К памятке врачу</Link><Link className="btn secondary" to="/screenings/history">История результатов</Link></>:<button className="btn secondary" onClick={()=>{setResult(null);setErrors([]);window.scrollTo(0,0);}}>Исправить ответы</button>}</div>
 </div>:<form onSubmit={submit} noValidate className="stack">{draft.pending&&<DraftNotice at={draft.pending.at} onRestore={draft.restore} onDiscard={draft.discard}/>}
 <div className="callout"><strong>{s.mode==='clinical'?'Оценка со специалистом':s.mode==='external'?'Внешний опросник и запись результата':byAdult?'Отвечает '+s.respondents.map(r=>r==='parent'?'родитель':r==='teacher'?'учитель':'специалист').join(' или '):selfOnly?'Отвечает сам подросток':'Отвечает ребёнок или родитель'}</strong><p>{s.mode!=='embedded'||byAdult?s.instructions:'Если отвечает ребёнок, родитель не подсказывает ответы — можно только помочь прочитать вопрос. Заполнение добровольное, можно остановиться. Заранее обсудите, кто увидит сохранённые ответы.'+(selfOnly?'':' Родитель заполняет свою форму отдельно.')}</p></div>
 {s.mode!=='embedded'&&<section className="card"><h2>{s.mode==='clinical'?'Бланк и источник':'1. Откройте исходную форму'}</h2><a href={s.externalUrl} target="_blank" rel="noopener noreferrer" className="btn full" style={{marginTop:16}}>{s.externalLabel}<Icon name="external" size={16}/></a>{s.id==='ygtss'&&<button type="button" className="btn secondary full" style={{marginTop:12}} onClick={downloadClinicalForm}>Скачать русский рабочий бланк .pdf</button>}<p className="small muted" style={{marginTop:12}}>{s.mode==='clinical'?'Русский рабочий бланк и критерии ниже доступны без интернета. Ссылка на оригинал открывает сайт авторов; записи туда не передаются.':'Откроется другой сайт; нужен интернет. Приложение не передаёт туда ваши записи. После прохождения вернитесь и внесите баллы вручную.'}</p><Disclosure title="Почему тест открывается отдельно"><p className="small">{s.attribution}</p><p className="small">{s.id==='mchat'?<a href="https://www.mchatscreen.com/mchat-rf/translations/" target="_blank" rel="noopener noreferrer">Другие русские версии на сайте авторов</a>:s.id==='sdq'?<a href="https://www.sdqinfo.org/py/sdqinfo/c0.py" target="_blank" rel="noopener noreferrer">Официальные правила подсчёта SDQ</a>:null}</p></Disclosure></section>}
 <section className="card"><h2 style={{marginBottom:16}}>{s.mode!=='embedded'?'2. Запишите сведения':'Перед началом'}</h2><ChildQuickFill unit={s.ageUnit==='months'?'months':'years'} date={date} current={childLabel} onPick={(label,a)=>{setChildLabel(label);setAge(String(a));}}/><div className="formField"><label className="fieldLabel" htmlFor="screen-child">Имя или обозначение ребёнка</label><input className="input" id="screen-child" value={childLabel} onChange={e=>setChildLabel(e.target.value)} maxLength={60} placeholder="Можно написать: старший ребёнок" autoComplete="off"/><p className="small muted">Фамилия и дата рождения не нужны. Обозначение поможет не перепутать результаты разных детей.</p></div>
 <div className="formField"><label className="fieldLabel" htmlFor="screen-age">Возраст на дату прохождения ({s.ageUnit==='months'?'полных месяцев':'полных лет'})</label><input className="input" id="screen-age" type="number" inputMode="numeric" min={s.ageMin} max={s.ageMax} step="1" value={age} onChange={e=>setAge(e.target.value)}/><p className="small muted">Для этого варианта: {s.ageLabel}.</p></div>
 <div className="formField"><label className="fieldLabel" htmlFor="screen-date">Дата прохождения</label><input className="input" id="screen-date" type="date" max={localDate()} value={date} onChange={e=>{const next=e.target.value;setDate(next);const c=getChildren().find(x=>x.label===childLabel.trim());if(c&&/^\d{4}-\d{2}/.test(next))setAge(ageOf(c,next));}}/></div>
 <div className="formField"><label className="fieldLabel" htmlFor="screen-respondent">Кто заполнял</label><select id="screen-respondent" value={respondent} onChange={e=>{const next=e.target.value as Respondent;setRespondent(next);setMeasurements({});if(s.id==='snapiv'||s.forms){setAnswers(Array(formFor(s,next)?.questions.length||0).fill(-1));setImpact('');}}}>{s.respondents.map(r=><option value={r} key={r}>{respondentLabels[r]}</option>)}</select>{(s.id==='snapiv'||s.forms)&&<p className="small muted">При смене отвечающего ответы сбрасываются: у каждого своя форма.</p>}{s.id==='sdq'&&<p className="small muted">Выберите ту же роль, что указана на бланке P4-17, T4-17 или S11-17.</p>}</div>
 {s.requiresSourceForm&&<div className="formField"><label className="fieldLabel" htmlFor="screen-source-form">Исходный бланк / перевод</label><input id="screen-source-form" className="input" value={sourceForm} maxLength={240} onChange={e=>setSourceForm(e.target.value)}/><p className="small muted">Уточните версию, язык и источник фактически использованной формы.</p></div>}
 </section>
 {form&&<section aria-label="Вопросы опросника" className="stack"><div className="screeningProgress"><span>Заполнено {answers.filter(a=>a>=0).length} из {answers.length}</span><progress aria-label="Прогресс заполнения" value={answers.filter(a=>a>=0).length} max={answers.length}/></div><div className="card soft"><h2>{form.instructions||s.instructions}</h2><p className="small muted" style={{marginTop:10}}>Выберите один ответ в каждой строке. {s.workingTranslation?'Перевод сделан для «Коры»: формулировки могут немного отличаться от других русских переводов.':'Формулировки исходного бланка сохранены.'}</p><p className="small" role="status">Ответов: {answers.filter(a=>a>=0).length} из {answers.length}</p></div>
 {form.questions.map((q,i)=><React.Fragment key={respondent+i}>{form.sections.some(sec=>sec.from===i&&sec.title)&&<h2 className="screeningSection">{sectionAt(form,i).title}</h2>}<fieldset className="screeningQuestion"><legend><span className="questionNumber">{i+1}.</span> {q}</legend><div className="screeningOptions">{sectionAt(form,i).options.map((label,value)=><label className={'screeningOption '+(answers[i]===value?'chosen':'')} key={value}><input type="radio" name={'screen-q-'+i} value={value} checked={answers[i]===value} onChange={()=>setAnswers(old=>old.map((a,j)=>i===j?value:a))}/><span>{label}</span></label>)}</div>{i===8&&safety&&<div className="callout danger" role="alert" style={{marginTop:14}}><strong>Можно обратиться за помощью уже сейчас</strong><p>{screeningSafety}</p><Link className="textButton" to="/help">Срочная помощь</Link></div>}</fieldset></React.Fragment>)}
 {s.impactQuestion&&<div className="card"><label className="fieldLabel" htmlFor="screen-impact">{s.impactQuestion}</label><select id="screen-impact" value={impact} onChange={e=>setImpact(e.target.value)}><option value="">Не отвечать</option>{impactOptions.map((o,i)=><option key={o} value={i}>{o}</option>)}</select><p className="small muted">Дополнительный вопрос, в сумму баллов не входит.</p></div>}
 </section>}
 {s.mode==='external'&&<section className="card"><h2 style={{marginBottom:16}}>3. Перенесите баллы</h2><label className="fieldLabel" htmlFor="screen-total">{s.totalLabel||(s.id==='mchat'?'Исходный балл M-CHAT-R (0–20)':'Общий балл трудностей SDQ (0–40)')}</label><input className="input" id="screen-total" type="number" inputMode="numeric" min="0" max={s.totalMax||(s.id==='mchat'?20:40)} step="1" value={total} onChange={e=>{setTotal(e.target.value);setFollowUpDone('');setFollowUpScore('');}}/>
 {s.id==='mchat'&&follow&&<div className="formField"><label className="fieldLabel" htmlFor="screen-followup">Проведено ли уточняющее интервью Follow-Up?</label><select id="screen-followup" value={followUpDone} onChange={e=>{setFollowUpDone(e.target.value);setFollowUpScore('');}}><option value="">Выберите</option><option value="no">Нет / пока не знаю</option><option value="yes">Да, проведено по официальному протоколу</option></select><p className="small muted">Это уточняющее интервью по исходным пунктам риска, а не повторное заполнение всех 20 вопросов.</p>{followUpDone==='yes'&&<div className="formField"><label className="fieldLabel" htmlFor="screen-followup-score">Сколько пунктов риска осталось после Follow-Up?</label><input className="input" id="screen-followup-score" type="number" inputMode="numeric" min="0" max={Number(total)} step="1" value={followUpScore} onChange={e=>setFollowUpScore(e.target.value)}/></div>}</div>}
 {s.id==='sdq'&&<><p className="small muted" style={{marginTop:10}}>Общий балл — сумма эмоциональных трудностей, поведения, гиперактивности и отношений со сверстниками. Просоциальное поведение не включают.</p><Disclosure title="Добавить субшкалы SDQ (необязательно)"><div className="medFields">{sdqFields.map(f=><div key={f.id}><label htmlFor={'sdq-'+f.id}>{f.label} · 0–10</label><input id={'sdq-'+f.id} className="input" type="number" inputMode="numeric" min="0" max="10" step="1" value={subscales[f.id]||''} onChange={e=>setSubscales(old=>({...old,[f.id]:e.target.value}))}/></div>)}</div></Disclosure></>}
 </section>}
 {s.id==='ygtss'&&<ClinicalInventory selected={ticInventory} onChange={setTicInventory}/>}
 <ExtraScaleFields s={s} respondent={respondent} values={measurements} setValues={setMeasurements} confirmed={clinicianConfirmed} setConfirmed={setClinicianConfirmed}/>
 <section className="card"><label className="fieldLabel" htmlFor="screen-notes">Заметка для врача (необязательно)</label><textarea id="screen-notes" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={3000} placeholder="Что мешает, как давно, что происходило в этот период; для внешнего теста — версия и источник"/></section>
 {!!errors.length&&<div className="callout danger" role="alert" ref={errorsRef} tabIndex={-1}><strong>Проверьте заполнение</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}
 <p className="small muted">Ответы сохранятся только после кнопки сохранения на следующем экране. До этого не закрывайте страницу. Записи доступны людям, у которых есть доступ к этому браузеру.</p>
 <button type="submit" className="btn full">{s.mode==='embedded'?'Получить результат':s.mode==='clinical'?'Рассчитать показатели':'Проверить внесённый результат'}<Icon name="arrow" size={17}/></button>
 <Disclosure title="Что этот опросник может и чего не может"><p>{s.limitations}</p><p className="small muted">{s.attribution}</p></Disclosure><Sources items={s.sources}/>
 </form>}</div>;
}
