import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {useVisit} from '../lib/useVisit';
import {addVisitQuestion,clearVisit,getVisit,removeChecklist,removeVisitMedication,removeVisitQuestion,setVisitMedicationField,MedDetail} from '../lib/visit';
import {medicationById} from '../lib/content';
import {copyText,downloadFile,downloadText,formatVisit,shareText} from '../lib/export';
import {toast} from '../lib/toast';
import PageHeader from '../components/PageHeader';
import Disclosure from '../components/Disclosure';
import Icon from '../components/Icon';
import {useJournals} from '../lib/useJournals';
import {useScreenings} from '../lib/useScreenings';
import {includeJournals,journalPeriod} from '../lib/journals';
import {journalTemplate} from '../lib/journalContent';
import {includeScreening} from '../lib/screenings';
import {screenerById,respondentLabels} from '../lib/screeningContent';
import {useAppointment} from '../lib/useAppointment';
import {appointmentIcs,clearAppointment,countdownLabel,daysUntil,formatAppointment,setAppointment} from '../lib/appointment';
import {isTelegram,shareToTelegram} from '../lib/twa';
const fields:{id:keyof MedDetail;label:string;placeholder:string}[]=[
 {id:'dose',label:'Доза из назначения врача',placeholder:'Перепишите из заключения'},
 {id:'schedule',label:'Как принимать по назначению',placeholder:'Время и кратность'},
 {id:'goal',label:'Что должно измениться',placeholder:'Какую трудность хотим уменьшить'},
 {id:'monitoring',label:'Что отслеживать',placeholder:'О чём договорились с врачом'},
 {id:'warnings',label:'Когда связаться с врачом',placeholder:'Важные предупреждения'},
 {id:'note',label:'Моя заметка',placeholder:'Например, что хочу уточнить'}
];
export default function VisitSheet() {
 const visit=useVisit(),results=useScreenings(),journals=useJournals(),appointment=useAppointment(),[newQ,setNewQ]=useState('');
 const days=appointment?daysUntil(appointment.date):0;
 const snapshots=Object.values(visit.checklists),recordCount=visit.questions.length+visit.meds.length+snapshots.length,selectedResults=results.filter(r=>r.includeInVisit),selectedJournals=journals.filter(r=>r.includeInVisit),count=recordCount+selectedResults.length+selectedJournals.length;
 const add=()=>{if(newQ.trim()&&addVisitQuestion(newQ)){setNewQ('');toast('Вопрос сохранён');}};
 const copy=async()=>{const ok=await copyText(formatVisit(getVisit()));toast(ok?'Памятка скопирована':'Не удалось скопировать. Попробуйте скачать памятку.',{variant:ok?'success':'error'});};
 // Share sheet of the phone, then Telegram's "send to chat", then the clipboard.
 const share=async()=>{const text=formatVisit(getVisit());if(await shareText(text)!=='unavailable'||shareToTelegram(text))return;const ok=await copyText(text);toast(ok?'Текст скопирован: вставьте его в сообщение':'Не удалось отправить. Скачайте памятку.',{variant:ok?'info':'error'});};
 const saveDate=(patch:{date?:string;time?:string;with?:string})=>{if(!setAppointment(patch))toast('Не удалось сохранить дату',{variant:'error'});};
 return <div className="container"><PageHeader title="Памятка к приёму" subtitle="Всё, что хочется обсудить, — в одном месте." eyebrow="Ваши записи"/>
 {count>0?<><div className="visitProgress"><Icon name="note" size={27}/><div><strong>Памятка собирается</strong><p>Вопросов: {visit.questions.length} · назначений: {visit.meds.length} · наблюдений: {snapshots.length} · результатов тестов: {selectedResults.length} · дневников: {selectedJournals.length}</p></div></div><div className="visitActions"><button className="btn" onClick={copy}><Icon name="copy" size={18}/>Скопировать</button><button className="btn secondary" onClick={share}><Icon name="share" size={18}/>Отправить</button><button className="btn secondary" onClick={()=>downloadText(formatVisit(getVisit()))}><Icon name="download" size={18}/>Скачать .txt</button>{!isTelegram()&&<button className="btn secondary" onClick={()=>window.print()}><Icon name="print" size={18}/>Печать / PDF</button>}</div></>:<div className="emptyState" style={{marginBottom:19}}><Icon name="note" size={33}/><h3>Здесь будет ваша памятка</h3><p>Добавляйте вопросы из карточек или запишите свой ниже. Перед приёмом всё можно сохранить одним файлом.</p><div className="buttonRow"><Link to="/diagnoses/adhd" className="btn secondary">Начать с СДВГ</Link><Link to="/review" className="btn secondary">Разобрать назначение</Link></div></div>}
 <div className="stack">
 <section className="card noPrint" aria-labelledby="appointment-title"><h2 id="appointment-title">Дата приёма</h2><p className="small muted">Дата попадёт в памятку и на главный экран. Напоминание можно добавить в календарь телефона.</p>
 <div className="appointment" style={{marginTop:14}}><div><label className="fieldLabel" htmlFor="visit-date">Дата</label><input className="input" id="visit-date" type="date" value={appointment?.date||''} onChange={e=>saveDate({date:e.target.value})}/></div>
 {appointment&&<><div><label className="fieldLabel" htmlFor="visit-time">Время</label><input className="input" id="visit-time" type="time" value={appointment.time||''} onChange={e=>saveDate({time:e.target.value})}/></div>
 <div className="wide"><label className="fieldLabel" htmlFor="visit-with">К кому</label><input className="input" id="visit-with" type="text" maxLength={200} placeholder="Например, детский психиатр" value={appointment.with||''} onChange={e=>saveDate({with:e.target.value})}/></div></>}</div>
 {appointment&&<><p className="appointmentWhen" role="status">{days>=0?'Приём '+countdownLabel(days):'Эта дата прошла. Укажите следующий приём.'}</p>
 <div className="buttonRow" style={{marginTop:12,alignItems:'center'}}>{days>=0&&<button className="btn secondary compact" style={{flex:'0 1 auto'}} onClick={()=>downloadFile(appointmentIcs(appointment),'PsyParent-priyom-'+appointment.date+'.ics','text/calendar;charset=utf-8')}><Icon name="calendar" size={16}/>Добавить в календарь</button>}<button className="textButton" onClick={()=>{if(!clearAppointment())toast('Не удалось убрать дату',{variant:'error'});}}>Убрать дату</button></div></>}
 </section>
 {appointment&&<p className="printOnly">Приём: {formatAppointment(appointment)}</p>}
 {!!results.length&&<section className="card"><h2>Результаты тестов и шкал</h2><p className="small muted" style={{marginTop:10}}>В экспорт попадут только отмеченные результаты, включая ответы и пояснения. Проверьте, чьи записи вы передаёте. Снятие отметки сохраняет результат в истории.</p>{results.map(r=>{const s=screenerById(r.screenerId)!;return <div className="visitItem" key={r.id}><h3><Link to={'/screenings/result/'+r.id}>{s.name} · {r.score.total} / {r.score.max}</Link></h3><p className="small muted">{r.childLabel} · {r.completedDate} · {respondentLabels[r.respondent]}</p><p className="small">{r.score.label}</p><label className="selectionCheck"><input type="checkbox" checked={r.includeInVisit} onChange={e=>{if(!includeScreening(r.id,e.target.checked))toast('Не удалось изменить выбор',{variant:'error'});}}/><span>Включить в памятку врачу</span></label></div>;})}<Link to="/screenings/history" className="textButton">История и удаление результатов</Link></section>}
 <section className="card"><h2>Дневники и формы</h2><p className="small muted" style={{marginTop:10}}>В памятку включены только выбранные записи. Проверьте ребёнка, даты и сведения, которые хотите передать.</p>{selectedJournals.map(r=><div className="visitItem" key={r.id}><h3><Link to={'/forms/record/'+r.id}>{journalTemplate(r.templateId)?.title}</Link></h3><p className="small">{r.childLabel} · {journalPeriod(r)}</p><p className="small muted">{respondentLabels[r.respondent]}{r.observerLabel?' · '+r.observerLabel:''}</p><label className="selectionCheck"><input type="checkbox" checked onChange={()=>{if(!includeJournals([r.id],false))toast('Не удалось изменить выбор',{variant:'error'});}}/><span>Включить в памятку врачу</span></label></div>)}{!selectedJournals.length&&<p className="small">{journals.length?'Сохранённые дневники пока не выбраны для памятки.':'Сюда можно добавить наблюдения из дневников сна, поведения, лечения и других форм.'}</p>}<div className="buttonRow"><Link className="textButton" to="/forms/history">Выбрать записи из истории</Link><Link className="textButton" to="/forms">Добавить наблюдение</Link></div></section>
 <section className="card noPrint"><h2 style={{marginBottom:13}}>Мой вопрос врачу</h2><label className="fieldLabel" htmlFor="custom-question">Что хочется уточнить?</label><textarea id="custom-question" placeholder="Например: как понять, что лечение помогает?" value={newQ} onChange={e=>setNewQ(e.target.value)} maxLength={3000}/><button className="btn full" style={{marginTop:10}} disabled={!newQ.trim()} onClick={add}><Icon name="plus" size={17}/>Добавить вопрос</button></section>
 {!!visit.questions.length&&<section className="card"><h2 style={{marginBottom:19}}>Вопросы врачу</h2>{visit.questions.map((q,i)=><div className="visitItem" key={q}><div className="visitItemTop"><span className="stepNumber">{i+1}</span><p>{q}</p><button className="iconButton" aria-label={'Удалить вопрос '+(i+1)} onClick={()=>removeVisitQuestion(q)}><Icon name="trash" size={16}/></button></div></div>)}</section>}
 {!!snapshots.length&&<section className="card"><h2 style={{marginBottom:19}}>Мои наблюдения</h2>{snapshots.map(c=><div className="visitItem" key={c.id}><div className="visitItemTop"><div><h3>{c.title}</h3><p className="small muted">{c.migrated?'Перенесено из предыдущей версии':c.updatedAt?'Обновлено '+new Date(c.updatedAt).toLocaleDateString('ru-RU'):''}</p></div><button className="iconButton" aria-label={'Удалить наблюдения: '+c.title} onClick={()=>removeChecklist(c.id)}><Icon name="trash" size={16}/></button></div><ul className="small">{c.lines.map((line,i)=><li key={i}>{line}</li>)}</ul>{!c.id.startsWith('legacy-')&&<Link className="textButton" to={'/diagnoses/'+c.id+'?tab=visit'}>Вернуться к карточке</Link>}</div>)}</section>}
 {!!visit.meds.length&&<section className="card"><h2 style={{marginBottom:8}}>Назначения для обсуждения</h2><p className="small muted" style={{marginBottom:20}}>Перепишите данные из заключения. Поля сохраняются при вводе. Приложение не проверяет и не рассчитывает дозу.</p>{visit.meds.map(id=>{const m=medicationById(id),name=m?.name||id,d=visit.medDetails[id]||{};return <div className="visitItem" key={id}><div className="visitItemTop"><div><h3>{name}</h3>{m&&<Link className="textButton" to={'/medications/'+id}>Открыть карточку</Link>}</div><button className="iconButton" aria-label={'Удалить назначение: '+name} onClick={()=>removeVisitMedication(id)}><Icon name="trash" size={16}/></button></div><Disclosure title="Доза, цель и мои заметки"><div className="medFields">{fields.map(f=><div key={f.id}><label htmlFor={id+'-'+f.id}>{f.label}</label><textarea rows={2} id={id+'-'+f.id} value={d[f.id]||''} maxLength={3000} placeholder={f.placeholder} onChange={e=>setVisitMedicationField(id,f.id,e.target.value)}/></div>)}</div></Disclosure></div>;})}</section>}
 </div>
 <div className="privacyNote"><Icon name="shield" size={16}/><span>Записи хранятся в этом браузере. Они не отправляются врачу автоматически и не появятся на другом устройстве. <Link to="/about">Подробнее</Link></span></div>
 {!!recordCount&&<button className="textButton danger" onClick={()=>{if(window.confirm('Удалить вопросы, назначения и сохранённые наблюдения из памятки? Отметки в карточках и история скринингов и дневников останутся.')){if(clearVisit())toast('Памятка очищена');}}}>Очистить вопросы, назначения и наблюдения</button>}
 </div>;
}
