#!/usr/bin/env python3
"""Subset Liberation Sans (SIL OFL 1.1) for PDF export and save it as base64 in webapp/src/lib/pdf/fontData.ts.

The OFL reserves the name «Liberation» for the original fonts, so the subset is renamed «Kora PDF Sans».
Run once after changing the character ranges: python3 tools/build_pdf_font.py
"""
from pathlib import Path
import base64, io
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
SRC = Path('/usr/share/fonts/truetype/liberation')
RANGES = [(0x20, 0x7e), (0xa0, 0xff), (0x100, 0x17f), (0x400, 0x45f), (0x490, 0x491), (0x2010, 0x2026), (0x2030, 0x2030),
          (0x2039, 0x203a), (0x20bd, 0x20bd), (0x2116, 0x2116), (0x2190, 0x2193), (0x2212, 0x2212), (0x2264, 0x2265)]
wanted = [c for a, b in RANGES for c in range(a, b + 1)]

def build(name, style):
    font = TTFont(SRC / name)
    cmap = font.getBestCmap()
    have = sorted(c for c in wanted if c in cmap)
    opts = subset.Options()
    opts.layout_features = ['kern']
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=have)
    sub.subset(font)
    for rec in font['name'].names:
        text = rec.toUnicode()
        if rec.nameID in (1, 3, 4, 6, 16, 17):
            text = text.replace('Liberation Sans', 'Kora PDF Sans').replace('LiberationSans', 'KoraPDFSans')
            rec.string = text
    buf = io.BytesIO()
    font.save(buf)
    return base64.b64encode(buf.getvalue()).decode('ascii'), have

regular, have = build('LiberationSans-Regular.ttf', 'normal')
bold, have_bold = build('LiberationSans-Bold.ttf', 'bold')
chars = sorted(set(have) & set(have_bold))
# Compact ranges of supported code points for the text sanitizer.
ranges, start, prev = [], chars[0], chars[0]
for c in chars[1:]:
    if c != prev + 1:
        ranges.append((start, prev)); start = c
    prev = c
ranges.append((start, prev))
out = root / 'webapp/src/lib/pdf/fontData.ts'
out.write_text(
    '// Generated by tools/build_pdf_font.py from Liberation Sans 2 (SIL Open Font License 1.1, see LICENSE-font.txt).\n'
    '// Subset to Latin, Cyrillic and common punctuation; renamed as the OFL requires for modified versions.\n'
    f'export const SUPPORTED:[number,number][]={[list(r) for r in ranges]};\n'
    f"export const REGULAR='{regular}';\n"
    f"export const BOLD='{bold}';\n", encoding='utf-8')
print(out, out.stat().st_size, 'bytes;', len(chars), 'characters')
