import snapiv from '../content/snapiv.json';
import type {Source} from './content';
import {embeddedScreeners} from './embeddedInstruments';
export type ScreeningId='phq9'|'gad7'|'mchat'|'sdq'|'assq'|'vanderbilt'|'ygtss'|'rcads25'|'crafft'|'snapiv'|'psc17'|'scared'|'vanderbilt2002';
export type FormSection={from:number;options:string[];scores?:number[];title?:string};
export type ScreenerForm={questions:string[];sections:FormSection[];instructions?:string};
export type Respondent='self'|'parent'|'teacher'|'clinician';
export const respondentLabels:Record<Respondent,string>={self:'Сам ребёнок / подросток',parent:'Родитель / заботящийся взрослый',teacher:'Учитель',clinician:'Специалист совместно с семьёй'};
export type Screener={id:ScreeningId;name:string;title:string;summary:string;mode:'embedded'|'external'|'clinical';ageMin:number;ageMax:number;ageUnit:'years'|'months';ageLabel:string;duration:string;respondents:Respondent[];version:string;translation:string;instructions:string;questions?:string[];options?:string[];impactQuestion?:string;limitations:string;attribution:string;sources:Source[];externalUrl?:string;externalLabel?:string;totalMax?:number;totalLabel?:string;requiresSourceForm?:boolean;related:string[];forms?:Partial<Record<Respondent,ScreenerForm>>;hidden?:boolean;workingTranslation?:boolean};
const rights={label:'PHQ Screeners: свободное воспроизведение PHQ и GAD-7 и их переводов',url:'https://www.phqscreeners.com/select-screener'};
const manual={label:'Авторы PHQ / GAD-7: руководство по использованию и подсчёту',url:'https://www.phqscreeners.com/images/sites/g/files/g10016261/f/201412/instructions.pdf'};
const credit='Разработано Robert L. Spitzer, Janet B.W. Williams, Kurt Kroenke и коллегами при поддержке образовательного гранта Pfizer Inc. Воспроизведение, перевод, показ и распространение разрешены.';
export const screeners:Screener[]=[
 ...embeddedScreeners,
 snapiv as Screener,
 {id:'mchat',name:'M-CHAT-R/F',title:'Ранние признаки аутизма',summary:'Опросник для родителей малышей. Важны исходный балл и, когда требуется, уточняющее интервью Follow-Up.',mode:'external',ageMin:16,ageMax:30,ageUnit:'months',ageLabel:'16–30 месяцев',duration:'Внешний опросник',respondents:['parent'],version:'mchat-rf-record-1',translation:'Русская версия, выбранная на сайте авторов; результат внесён пользователем',instructions:'По ссылке доступен первый этап — M-CHAT-R. Перенесите его исходный балл. При 3–7 баллах нужно уточняющее интервью Follow-Up с подготовленным специалистом; его результат можно внести отдельно. Сохраните также исходный отчёт: PsyParent не получает ответы с внешнего сайта.',limitations:'Скрининг не подтверждает и не исключает РАС. При утрате навыков или других признаках трудностей нужна оценка развития независимо от балла. M-CHAT-R/F не предназначен для старших детей.',attribution:'M-CHAT-R/F © Diana Robins, Deborah Fein, Marianne Barton. Вопросы и схемы интервью здесь не воспроизводятся. Распространение электронной версии требует разрешения правообладателей.',externalUrl:'https://test.autism.help/',externalLabel:'Открыть русский M-CHAT-R',sources:[{label:'Сайт авторов: русские версии и ссылка на test.autism.help',url:'https://www.mchatscreen.com/mchat-rf/translations/'},{label:'Авторы: правила подсчёта M-CHAT-R/F',url:'https://www.mchatscreen.com/mchat-rf/scoring/'},{label:'Авторы: условия электронного использования',url:'https://www.mchatscreen.com/mchat-rf/'}],related:['asd','developmental_delay']},
 {id:'sdq',name:'SDQ',title:'Эмоции, поведение и внимание',summary:'Сильные стороны и трудности ребёнка в нескольких сферах. Родитель, учитель и подросток заполняют разные версии.',mode:'external',ageMin:4,ageMax:17,ageUnit:'years',ageLabel:'4–17 лет; самоотчёт с 11 лет',duration:'Внешний бланк',respondents:['parent','teacher','self'],version:'sdq-record-1',translation:'Официальная русская версия SDQ P4-17 / T4-17 / S11-17; внесённый результат',instructions:'На сайте авторов выберите русскую версию для нужного возраста и отвечающего. Попросите специалиста выполнить подсчёт по официальным правилам или используйте сервис авторов SDQscore. Перенесите полученный общий балл трудностей. Пять субшкал можно добавить отдельно. Если подсчёт неясен, возьмите заполненный бланк на приём.',limitations:'SDQ не устанавливает СДВГ или другой диагноз. Порог зависит от версии, возраста и нормативов: приложение сохраняет баллы без категории «норма / расстройство». Ответы разных людей не складывают и не усредняют.',attribution:'SDQ © Robert Goodman / Youthinmind. Для электронной версии нужно разрешение. Здесь — ссылка на официальный бланк и запись уже полученного результата.',externalUrl:'https://www.sdqinfo.org/py/sdqinfo/b3.py?language=Russian',externalLabel:'Открыть русские бланки SDQ',sources:[{label:'SDQ: официальные русские бланки',url:'https://www.sdqinfo.org/py/sdqinfo/b3.py?language=Russian'},{label:'SDQ: правила подсчёта',url:'https://www.sdqinfo.org/py/sdqinfo/c0.py'},{label:'SDQ: условия использования',url:'https://www.sdqinfo.org/'}],related:['adhd','anxiety_overview','behavior_overview']},
 {id:'phq9',name:'PHQ-9',title:'Депрессивные симптомы',summary:'Девять вопросов о последних двух неделях. Отвечает сам подросток, а не родитель за него.',mode:'embedded',ageMin:13,ageMax:17,ageUnit:'years',ageLabel:'13–17 лет · самоотчёт',duration:'Около 3 минут',respondents:['self'],version:'phq9-ru-1',translation:'Стандартный PHQ-9, русская версия PHQ Screeners (MDM Portal, 43796); не PHQ-A',instructions:'Как часто за последние 2 недели Вас беспокоили следующие проблемы?',questions:[
 'Вам не хотелось ничего делать',
 'У Вас было плохое настроение, Вы были подавлены или испытывали чувство безысходности',
 'Вам было трудно заснуть, у Вас был прерывистый сон, или Вы слишком много спали',
 'Вы были утомлены, или у Вас было мало сил',
 'У Вас был плохой аппетит, или Вы переедали',
 'Вы плохо о себе думали: Вы считали себя неудачником (неудачницей), или были в себе разочарованы, или считали, что подвели свою семью',
 'Вам было трудно сосредоточиться (например, на чтении газеты или на просмотре телепередач)',
 'Вы двигались или говорили настолько медленно, что окружающие это замечали? Или, наоборот, Вы были настолько суетливы или взбудоражены, что двигались гораздо больше обычного',
 'Вас посещали мысли о том, что Вам лучше было бы умереть, или о том, чтобы причинить себе какой-нибудь вред'
 ],options:['Ни разу','Несколько дней','Более половины дней','Почти каждый день'],impactQuestion:'Если Вы положительно ответили на какие-нибудь пункты, то оцените, насколько трудно Вам было работать, заниматься домашними делами или общаться с людьми из-за этих проблем?',limitations:'Это стандартный PHQ-9, а не подростковая модификация PHQ-A. Есть исследования PHQ-9 в возрасте 13–17 лет, но это не подтверждает отдельную валидизацию данной электронной русской версии для всех подростков. Диапазоны описывают сумму симптомов, а не диагноз или безопасность. Раздражительность, другие болезни и обстоятельства требуют беседы с врачом.',attribution:credit,sources:[rights,manual,{label:'Русские формулировки PHQ-9: MDM Portal Университета Мюнстера, из PHQ Screeners',url:'https://medical-data-models.org/43796?form-lang=ru'},{label:'Richardson et al., 2010: исследование PHQ-9 у подростков 13–17 лет',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3217785/'}],related:['depression','mood_overview']},
 {id:'gad7',name:'GAD-7',title:'Тревожные симптомы',summary:'Семь вопросов о тревоге за последние две недели. Отвечает сам подросток.',mode:'embedded',ageMin:12,ageMax:17,ageUnit:'years',ageLabel:'12–17 лет · самоотчёт',duration:'Около 2 минут',respondents:['self'],version:'gad7-ru-1',translation:'GAD7 Russian for Russia, PHQ Screeners / Pfizer; бланк Project TEACH',instructions:'Как часто Вас за последние 14 дней беспокоили следующие проблемы?',questions:[
 'Вы нервничали, тревожились или испытывали сильный стресс',
 'Вы были неспособны успокоиться или контролировать свое волнение',
 'Вы слишком сильно волновались по различным поводам',
 'Вам было трудно расслабиться',
 'Вы были настолько суетливы, что Вам было тяжело усидеть на месте',
 'Вы легко злились или раздражались',
 'Вы испытывали страх, словно должно произойти нечто ужасное'
 ],options:['Ни разу','Несколько дней','Более недели','Почти каждый день'],limitations:'GAD-7 не охватывает все детские тревожные расстройства. Исследования в 12–17 лет не означают, что стандартные взрослые диапазоны являются диагностическими порогами для русскоязычного подростка. Здесь они служат ориентиром выраженности симптомов и поводом для обсуждения.',attribution:credit,sources:[rights,manual,{label:'Русский бланк GAD-7: Project TEACH, программа помощи врачам штата Нью-Йорк',url:'https://projectteachny.org/app/uploads/2022/07/GAD7_Russian-for-Russia.pdf'},{label:'Mossman et al., 2017: GAD-7 у подростков 12–17 лет',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC5765270/'}],related:['gad','anxiety_overview']},
 {id:'assq',name:'ASSQ',title:'Аутистические особенности в школьном возрасте',summary:'Наблюдения родителя или учителя. Для школьников; не заменяет оценку развития.',mode:'external',ageMin:7,ageMax:16,ageUnit:'years',ageLabel:'7–16 лет',duration:'27 пунктов · внешний доступ',respondents:['parent','teacher'],version:'assq-record-1',translation:'ASSQ, исходная форма 27 пунктов; язык и источник указывает пользователь',requiresSourceForm:true,totalMax:54,totalLabel:'Сумма ASSQ (0–54)',instructions:'Получите доступ к исходной форме ASSQ через сайт авторов или у специалиста с разрешением на её использование. С 15 июня 2026 года доступ платный через ESSENCE-IN, если нет отдельного соглашения. Здесь можно сохранить уже полученный балл. Не переносите сюда ASSQ-REV: это другая версия.',limitations:'ASSQ — скрининг, не диагноз. Пороги различаются в зависимости от выборки, страны и отвечающего. Приложение не присваивает категорию по единому порогу и не подтверждает валидизацию использованного перевода. Оценки родителя и учителя сохраняют отдельно.',attribution:'ASSQ: Ehlers, Gillberg, Wing. С 15.06.2026 авторы изменили условия доступа, включая бумажные копии. Вопросы в PsyParent не воспроизводятся.',externalUrl:'https://www.gu.se/en/gnc/gncs-resources/screening-questionnaires-and-protocols/assq-autism-spectrum-screening-questionnaire-and-assq-rev',externalLabel:'Условия и доступ к ASSQ',sources:[{label:'University of Gothenburg: ASSQ, подсчёт и новые условия доступа',url:'https://www.gu.se/en/gnc/gncs-resources/screening-questionnaires-and-protocols/assq-autism-spectrum-screening-questionnaire-and-assq-rev'},{label:'Ehlers et al., 1999: исходное исследование ASSQ',url:'https://pubmed.ncbi.nlm.nih.gov/10382133/'},{label:'Adachi et al., 2018: возраст исходной стандартизации ASSQ 7–16 лет',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6038992/'}],related:['asd']},
 {id:'vanderbilt',name:'Vanderbilt',title:'Внимание, активность и влияние на жизнь',summary:'Начальная оценка СДВГ по отдельным наблюдениям родителя и учителя.',mode:'external',ageMin:6,ageMax:12,ageUnit:'years',ageLabel:'6–12 лет',duration:'Родитель / учитель · внешний бланк',respondents:['parent','teacher'],version:'vanderbilt-initial-record-1',translation:'NICHQ Vanderbilt, начальная форма первого издания 2002; оригинал на английском',requiresSourceForm:true,totalMax:54,totalLabel:'Сумма симптомов 1–18 (0–54)',instructions:'Откройте начальный бланк NICHQ для родителя или учителя и правила подсчёта. Официальная бесплатная форма — на английском. Если нужен русский перевод, обсудите его источник со специалистом и укажите его ниже. Перенесите результаты начального бланка; форма повторной оценки здесь не поддерживается. Обе оценки лучше принести врачу отдельными записями.',limitations:'Шкала не устанавливает СДВГ. Нужны беседа, история развития, влияние трудностей и сведения из разных ситуаций. Пороги относятся к этой форме; перевод или другая редакция могут требовать иной проверки. Баллы сопутствующих трудностей — повод для уточнения, не дополнительные диагнозы.',attribution:'NICHQ / American Academy of Pediatrics, 2002; Vanderbilt Rating Scales, Mark L. Wolraich. Первое издание доступно для скачивания у издателя. Вопросы и неутверждённый перевод в приложение не включены.',externalUrl:'https://nichq.org/downloadable/nichq-vanderbilt-assessment-scales/',externalLabel:'Открыть формы NICHQ (английский)',sources:[{label:'NICHQ: начальные формы Vanderbilt, возраст и редакции',url:'https://nichq.org/downloadable/nichq-vanderbilt-assessment-scales/'},{label:'NICHQ / AAP: бланки и правила подсчёта первого издания',url:'https://nichq.org/wp-content/uploads/2024/09/NICHQ-Vanderbilt-Assessment-Scales.pdf'}],related:['adhd','behavior_overview']},
 {id:'ygtss',name:'YGTSS-R',title:'Выраженность тиков и их влияние',summary:'Клиническая оценка за последнюю неделю. Баллы выставляет специалист вместе с семьёй.',mode:'clinical',ageMin:5,ageMax:17,ageUnit:'years',ageLabel:'5–17 лет · со специалистом',duration:'10 параметров + влияние на жизнь',respondents:['clinician'],version:'ygtss-r-2017-record-1',translation:'YGTSS-R, September 2017; русский рабочий бланк — неофициальный перевод',requiresSourceForm:true,totalLabel:'Общий балл тиков (0–50)',instructions:'Сначала специалист уточняет, какие движения и звуки являются тиками, и оценивает последнюю неделю по критериям бланка. В приложении доступны перечень тиков, критерии оценок и подсчёт. Русский рабочий PDF также доступен ниже; он не является отдельно валидированной русской версией. Это оценка выраженности, а не тест на наличие синдрома Туретта.',limitations:'Не предназначена для самостоятельной постановки диагноза родителем. Общий балл тиков 0–50, нарушение функционирования 0–50 и глобальный балл 0–100 — разные показатели. Более высокий балл не задаёт лечение автоматически. Сравнивать результаты лучше при одинаковой процедуре и с одним специалистом.',attribution:'YGTSS-R © J. Leckman, revised September 2017. Русский рабочий перевод предоставлен для этой версии приложения; не заявлен как валидированный. Сохранены авторские отметки исходного PDF.',externalUrl:'https://cps.ca/uploads/mh_tools/YGTSS-Clinician_Revised_2017.pdf',externalLabel:'Оригинальный YGTSS-R (английский)',sources:[{label:'Canadian Paediatric Society: оригинальный YGTSS-R, 2017',url:'https://cps.ca/uploads/mh_tools/YGTSS-Clinician_Revised_2017.pdf'},{label:'McGuire et al., 2018: исследование и пересмотр YGTSS',url:'https://pubmed.ncbi.nlm.nih.gov/29653992/'},{label:'Leckman et al., 1989: исходное исследование клинической шкалы',url:'https://pubmed.ncbi.nlm.nih.gov/2768151/'}],related:['tics_tourette']},
 {id:'rcads25',name:'RCADS-25',title:'Тревога и депрессивные симптомы',summary:'Более широкий взгляд на эмоциональные трудности ребёнка; отвечает сам ребёнок или подросток.',mode:'external',ageMin:8,ageMax:17,ageUnit:'years',ageLabel:'8–17 лет · самоотчёт',duration:'25 пунктов · русский бланк',respondents:['self'],version:'rcads25-youth-record-1',translation:'RCADS-25 Youth, Russian, UCLA Child FIRST, 2024',requiresSourceForm:true,totalMax:75,totalLabel:'Общая сумма RCADS-25 (0–75)',instructions:'На сайте UCLA выберите Russian 25-Item Youth Version. Заполните бланк и получите подсчёт по официальным ресурсам со специалистом. Перенесите общий сырой балл; баллы тревоги и депрессивных симптомов можно добавить отдельно. Это форма самоотчёта, не родительская версия и не RCADS-47.',limitations:'Сырой балл не равен T-баллу. Приложение не применяет иностранные нормативы автоматически и не переводит сумму в диагноз. Возраст инструмента у авторов 8–18 лет; здесь представлен детский маршрут 8–17 лет. Русский бланк на сайте авторов сам по себе не подтверждает отдельные российские нормы.',attribution:'RCADS © Bruce F. Chorpita и Susan H. Spence. Официальное распространение форм — через UCLA Child FIRST; вопросы и нормативные таблицы не копируются в приложение.',externalUrl:'https://rcads.ucla.edu/versions',externalLabel:'Открыть русскую форму RCADS-25',sources:[{label:'UCLA Child FIRST: RCADS, возраст и назначение',url:'https://rcads.ucla.edu/'},{label:'UCLA: официальная русская форма RCADS-25 Youth',url:'https://rcads.ucla.edu/versions'},{label:'UCLA: правила использования',url:'https://rcads.ucla.edu/permissions'},{label:'UCLA: подсчёт и нормативные ресурсы',url:'https://rcads.ucla.edu/scoringdownloads'}],related:['anxiety_overview','depression','gad']},
 {id:'crafft',name:'CRAFFT 2.1',title:'Употребление веществ и связанные риски',summary:'Конфиденциальный разговор подростка со специалистом об алкоголе и других веществах.',mode:'external',ageMin:12,ageMax:17,ageUnit:'years',ageLabel:'12–17 лет · самоотчёт',duration:'Русский бланк · со специалистом',respondents:['self'],version:'crafft21-record-1',translation:'CRAFFT 2.1 Self-administered, Russian, July 2021',requiresSourceForm:true,totalMax:6,totalLabel:'Баллы части CRAFFT (0–6)',instructions:'Откройте официальный русский бланк 2.1 и заполните его конфиденциально перед беседой со специалистом. Здесь можно записать полученную сумму и отметку риска поездок. На общем устройстве ответы могут увидеть другие: не сохраняйте их, если это небезопасно. По умолчанию эта запись не включается в общую памятку; выбор доступен после сохранения.',limitations:'Это скрининг, не диагноз зависимости. Возраст инструмента у авторов 12–21 год; в детском приложении 12–17 лет. Нулевая сумма не исключает риск и не отменяет обсуждение употребления. CRAFFT 2.1 не включает дополнительный блок никотина 2.1+N. Нужна конфиденциальная беседа; родитель не отвечает за подростка.',attribution:'CRAFFT © John R. Knight, Boston Children’s Hospital. Для электронной репродукции требуется согласование с CABHRe. Здесь официальная внешняя форма и сохранение её результата, без копирования вопросов.',externalUrl:'https://crafft.org/wp-content/uploads/2021/07/RUSSIAN_2.1_SELF_2021-07.pdf',externalLabel:'Открыть русский CRAFFT 2.1',sources:[{label:'Boston Children’s Hospital: русские формы и условия репродукции',url:'https://crafft.org/get-the-crafft/'},{label:'Авторы CRAFFT: проведение и конфиденциальность',url:'https://crafft.org/use-the-crafft/'},{label:'Руководство CRAFFT 2.1: возраст, подсчёт и дальнейшие действия',url:'https://crafft.org/wp-content/uploads/2021/10/CRAFFT_2.1_Provider-Manual_2021.10.28.pdf'}],related:['substance_use']}

];
for(const s of screeners)if(['assq','rcads25','vanderbilt'].includes(s.id))s.hidden=true;
export const catalogScreeners=screeners.filter(s=>!s.hidden);
export const screenerById=(id:string)=>screeners.find(s=>s.id===id);
export function formFor(s:Screener,respondent:Respondent):ScreenerForm|null{
 if(s.forms)return s.forms[respondent]||null;
 return s.questions?{questions:s.questions,sections:[{from:0,options:s.options!}]}:null;
}
export const sectionAt=(f:ScreenerForm,i:number)=>f.sections.reduce((cur,sec)=>i>=sec.from?sec:cur,f.sections[0]);
export const impactOptions=['Совсем не трудно','Немного трудно','Очень трудно','Чрезвычайно трудно'];
export const sdqFields=[{id:'emotional',label:'Эмоциональные трудности'},{id:'conduct',label:'Трудности поведения'},{id:'hyperactivity',label:'Гиперактивность / невнимательность'},{id:'peer',label:'Отношения со сверстниками'},{id:'prosocial',label:'Просоциальное поведение'}] as const;
export const screeningSafety='Если мысли о смерти или причинении вреда себе есть, расскажите безопасному взрослому и свяжитесь со специалистом сегодня. Если есть намерение действовать, недавняя попытка или трудно оставаться в безопасности — не оставайтесь в одиночестве, обратитесь в экстренную службу: в России 112, в другой стране — местный номер. Тест не оценивает непосредственную опасность.';

export type ScaleField={id:string;label:string;min?:number;max:number;step?:number;optional?:boolean};
export const ticDimensions=['Количество','Частота','Интенсивность','Сложность','Помехи действию или речи'];
export function scaleFields(id:ScreeningId,respondent:Respondent):ScaleField[]{
 if(id==='ygtss')return [...['motor','vocal'].flatMap(kind=>ticDimensions.map((label,i)=>({id:kind+i,label:(kind==='motor'?'Моторные':'Вокальные')+' · '+label,max:5}))),{id:'impairment',label:'Нарушение функционирования',max:50,step:10}];
 if(id==='vanderbilt')return [{id:'inattention',label:'Пунктов 1–9 с ответом 2 или 3',max:9},{id:'hyperactivity',label:'Пунктов 10–18 с ответом 2 или 3',max:9},{id:'performance',label:'Пунктов функционирования с ответом 4 или 5',max:8},...(respondent==='parent'?[{id:'opposition',label:'Оппозиционные проявления: пунктов 19–26 с ответом 2 или 3',max:8,optional:true},{id:'conduct',label:'Нарушения поведения: пунктов 27–40 с ответом 2 или 3',max:14,optional:true}]:[{id:'oppositionConduct',label:'Оппозиционные проявления / поведение: пунктов 19–28 с ответом 2 или 3',max:10,optional:true}]),{id:'anxietyDepression',label:'Тревога / депрессия: пунктов '+(respondent==='parent'?'41–47':'29–35')+' с ответом 2 или 3',max:7,optional:true}];
 if(id==='rcads25')return [{id:'anxiety',label:'Сырой балл тревоги',max:45,optional:true},{id:'depression',label:'Сырой балл депрессивных симптомов',max:30,optional:true}];
 if(id==='crafft')return [{id:'car',label:'Отметка риска поездок (пункт CAR): нет — 0, да — 1',max:1}];
 return [];
}
export const screeningDomains:Record<ScreeningId,string[]>={psc17:['Эмоции','Поведение и внимание'],scared:['Эмоции'],vanderbilt2002:['Поведение и внимание'],snapiv:['Поведение и внимание'],mchat:['Развитие и общение'],assq:['Развитие и общение'],sdq:['Поведение и внимание','Эмоции'],vanderbilt:['Поведение и внимание'],phq9:['Эмоции'],gad7:['Эмоции'],rcads25:['Эмоции'],ygtss:['Тики'],crafft:['Употребление веществ']};
export const screeningModeLabel=(s:Screener)=>s.mode==='clinical'?'Со специалистом':s.mode==='embedded'?'Пройти здесь':s.id==='assq'?'Внешний доступ · платно':'Внешняя форма';
export function matchesScreeningAge(s:Screener,age:number,unit:'years'|'months'){
 const months=unit==='years'?age*12:age;
 const converted=s.ageUnit==='months'?months:Math.floor(months/12);
 return converted>=s.ageMin&&converted<=s.ageMax;
}
